<a href="https://colab.research.google.com/github/Shivamsamediya/Amazon-UI/blob/main/Linear_LogisiticRegression.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import pandas as pd
import seaborn as sns
import matplotlib.pyplot as plt

#upload csv file
from google.colab import files

uploaded = files.upload()

Saving laptop_prices.csv to laptop_prices (2).csv

In [ ]:
filename = list(uploaded.keys())[0]

df = pd.read_csv(filename)

df.head()

,Brand,Processor,RAM (GB),Storage,GPU,Screen Size (inch),Resolution,Battery Life (hours),Weight (kg),Operating System,Price ($)
0,Apple,AMD Ryzen 3,64,512GB SSD,Nvidia GTX 1650,17.3,2560x1440,8.9,1.42,FreeDOS,3997.07
1,Razer,AMD Ryzen 7,4,1TB SSD,Nvidia RTX 3080,14.0,1366x768,9.4,2.57,Linux,1355.78
2,Asus,Intel i5,32,2TB SSD,Nvidia RTX 3060,13.3,3840x2160,8.5,1.74,FreeDOS,2673.07
3,Lenovo,Intel i5,4,256GB SSD,Nvidia RTX 3080,13.3,1366x768,10.5,3.10,Windows,751.17
4,Razer,Intel i3,4,256GB SSD,AMD Radeon RX 6600,16.0,3840x2160,5.7,3.38,Linux,2059.83

In [ ]:
import re  # Regular expressions for extracting numbers

# Function to extract numeric storage capacity
def extract_storage(storage):
    if pd.isnull(storage):  # Handle NaN values
        return 0
    match = re.search(r'(\d+)', str(storage))  # Extract first number
    if match:
        value = int(match.group(1))  # Convert to integer
        if 'TB' in storage.upper():  # Convert TB to GB (1TB = 1000GB)
            return value * 1000
        return value
    return 0  # Default if no match

# Apply function to Storage column
df['Storage_Capacity'] = df['Storage'].apply(extract_storage)

# Drop old Storage column if not needed
df.drop(columns=['Storage'], inplace=True)

# Display first few rows
print(df[['Storage_Capacity']].head())

   Storage_Capacity
0               512
1              1000
2              2000
3               256
4               256

In [ ]:
#Linear Regression
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LinearRegression
from sklearn.metrics import mean_squared_error, r2_score

In [ ]:
# Selecting numerical features (modify based on dataset)
X = df[['RAM (GB)', 'Storage_Capacity', 'Screen Size (inch)']]
y = df['Price ($)']

In [ ]:
# Splitting into training and testing sets
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)

In [ ]:
# Initialize and train model
lr_model = LinearRegression()
lr_model.fit(X_train, y_train)

LinearRegression()

In [ ]:
import numpy as np

# Predictions
y_pred = lr_model.predict(X_test)

# Model evaluation
print("R² Score:", r2_score(y_test, y_pred))
print("RMSE:", np.sqrt(mean_squared_error(y_test, y_pred)))

R² Score: 0.3847799212223967
RMSE: 1044.134968065003

In [ ]:
## Done

In [ ]:
#Logistic Regression
from sklearn.linear_model import LogisticRegression
from sklearn.metrics import accuracy_score

In [ ]:
# Creating a binary classification column
df['Price_Category'] = (df['Price ($)'] > df['Price ($)'].median()).astype(int)

df.head()

,Brand,Processor,RAM (GB),GPU,Screen Size (inch),Resolution,Battery Life (hours),Weight (kg),Operating System,Price ($),Storage_Capacity,Price_Category
0,Apple,AMD Ryzen 3,64,Nvidia GTX 1650,17.3,2560x1440,8.9,1.42,FreeDOS,3997.07,512,1
1,Razer,AMD Ryzen 7,4,Nvidia RTX 3080,14.0,1366x768,9.4,2.57,Linux,1355.78,1000,0
2,Asus,Intel i5,32,Nvidia RTX 3060,13.3,3840x2160,8.5,1.74,FreeDOS,2673.07,2000,1
3,Lenovo,Intel i5,4,Nvidia RTX 3080,13.3,1366x768,10.5,3.10,Windows,751.17,256,0
4,Razer,Intel i3,4,AMD Radeon RX 6600,16.0,3840x2160,5.7,3.38,Linux,2059.83,256,1

In [ ]:
X = df[['RAM (GB)', 'Storage_Capacity', 'Screen Size (inch)']]
y = df['Price_Category']

In [ ]:
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)

# Train Logistic Regression model
log_reg = LogisticRegression()
log_reg.fit(X_train, y_train)

LogisticRegression()

In [ ]:
# Predictions
y_pred = log_reg.predict(X_test)

# Model evaluation
print("Accuracy:", accuracy_score(y_test, y_pred))

Accuracy: 0.7472387425658453

In [ ]:
## Done

In [ ]:
# Decision Trees
from sklearn.tree import DecisionTreeClassifier

# Train Decision Tree model
dt_model = DecisionTreeClassifier(max_depth=5, random_state=42)
dt_model.fit(X_train, y_train)

# Predictions
y_pred_dt = dt_model.predict(X_test)

# Model evaluation
print("Decision Tree Accuracy:", accuracy_score(y_test, y_pred_dt))

Decision Tree Accuracy: 0.7476635514018691